[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-store, max-age=0"